### ISSUE TITLE
Your add method is a little broken ☹️

### ISSUE THREAD

**Issue by AwesomeZaidi** [jshams/cs-1.3#1]
Sets can only have unique elements, also you're using the term items when the mathematical terminology here should be `elements` as items are used in a list. I would do some research on data types and data structures and consider not skipping your CS classes for made up religion events. 

So basically, in your add method you need to make sure that that element does not already exist :)

**Comment by jshams** [comment]
Thanks for the feedback! Please read and test my code before you comment. ;)
